excluded_packages = {
    ("3.0"): {
        "bioc_experiment--MafDb.ALL.wgs.phase1.release.v3.20101123": "newer in bioconductor-annotation",
        "bioc_experiment--MafDb.ESP6500SI.V2.SSA137.dbSNP138": "newer in bioconductor-annotation",
        "bioc_experiment--phastCons100way.UCSC.hg19": "newer in bioconductor-annotation",
        "cran--GOsummaries": "newer in bioconductor",
        "cran--gdsfmt": "newer in bioconductor",
        "cran--oposSOM": "newer in bioconductor",
        # level 0
        "SSOAP": "(omegahat / github only?)",
        # "RDCOMClient": "(omegahat / github only?)",
        "XMLRPC": "(omegahat / github only?)",
        "XMLSchema": "(omegahat / github only?)",
        "SVGAnnotation": "github only?",
        "qtpaint": "missing libQtCore.so.4 and was listed as broken in nixpkgs 15.09",
        "nloptr": "nlopt library is broken in nixpkgs 15.09",
        "HiPLARM": "build is broken, and the package never got any updates and was removed in 2017-07-02",
        "Rmosek": "build is broken according to R/default.nix",
        "bigGP": "build is broken",
        "SOD": "build broken without libOpenCL",
        "BRugs": "needs OpenBUGS, not in nixpkgs. Or in ubuntu. And the website change log says it hasn't updated since 2014. And the ssl certificate is expired.",
        "doMPI": "build is broken with mpi trouble",
        "pmclust": "build is broken with mpi trouble",
        "pbdSLAP": "build is broken with mpi trouble",
        "npRmpi": "build is broken with mpi trouble",
        "cudaBayesreg": "build is broken, needs nvcc",
        "permGPU": "build is broken, needs nvcc",
        "Rcplex": "cplex (c dependency) only shows up later in nixpkgs.",
        "RSAP": "misssing sapnwrfc.h",
        "jvmr": "broken build. Wants to talk to ddahl.org. Access /home/dahl during build",
        "rpanel": "build broken, wants DISPLAY?",
        "rgdal": "not compatible with GDAL2 (which is what's in nixpkgs at this point)",
        "rsbml": "libsmbl isn't packagd in nixpkg ",
        "sybilSBML": "configure checks for /usr/include and /usr/local/include - and possibly also needs libsmbl, judging by the name?",
        "interactiveDisplayBase": "wants to talk to bioconductor.org during installation",
        "RcppOctave": "build seems incompatible wit octave version in nixpkgs.",
        "SDMTools": "all downstreams fail with  undefined symbol: X",
        "oligoClasses": "requires biocInstaller during installation",
        "UniProt.ws": "wants to talk to uniprot.org",
        "BiocCheck": "requries BiocInstaller",
        "affy": "requries BiocInstaller",
        "MSeasyTkGUI": "Needs Tk",
        "ncdfFlow": "no hdf5.dev in this nixpkgs",
        "rhdf5": "no hdf5.dev in this nixpkgs",
        "ltsk": "missing lRlacpack und lRblas?",
        "clpAPI": "insists on /usr/include and /usr/local/include",
        "ROracle": "OCI libraries not found",
        "NCmisc": "requires BiocInstaller",
        "QuasR": "requires BiocInstaller",
        "trackViewer": "tcl issue",
        "RQuantLib": "hquantlib ( if that's even the right package) is broken in nixpgks 15.09)",
        "HilbertVisGUI": "needs OpenCL, not available in nixpkgs 15.09",
        "OpenCL": "needs OpenCL, not available in nixpkgs 15.09",
        # "gWidgetstcltk": "tcl invalid command name 'font'",
    },
    ("3.0", "<2014-10-26"): {
        "bioassayR": "wants RSQLite 1.0.0, which only appeared on 14-10-25",
        "plethy": "wants RSQLite 1.0.0, which only appeared on 14-10-25",
        "cummeRbund": "wants RSQLite 1.0.0, which only appeared on 14-10-25",
        "VariantFiltering": "wants RSQLite 1.0.0, which only appeared on 14-10-25",
    },
    ("3.0", "<2014-11-07"): {
        "HSMMSingleCell": "needs VGAM > 0.9.5, that shows up on 11-07",
    },
    ("3.0", "<2015-01-11"): {
        "easyRNASeq": "needs LSD>=3.0, which shows up on 2015-01-10",
        "seqplots": "needs shiny.>=0.11.0 which shows up on 2015-02-11",
        "MSGFgui": "needs shiny.>=0.11.0 which shows up on 2015-02-11",
    },
    ("3.7"): {
        "iontree": "deprecated in 3.6, removed in 3.7, but still in PACKAGES",
        "domainsignatures": "deprecated in 3.6, removed in 3.7, but still in PACKAGES",
    },
    # ("3.13", "<2021-07-01"): [
    # "ggtree",  # missing ggfun
    # ],
}
package_patches = {
    # this is the big gun
    # {'version': {'bioc|experiment|annotation': [{'name':..., 'version': ..., 'depends': [...], 'imports': [...], 'needs_compilation': True}]}}
    # "3.0": {
    #     "annotation": [
    #         {
    #             "name": "gahgu133plus2cdf",
    #             "version": "2.2.1",
    #             "depends": [
    #                 "utils",
    #                 "AnnotationDbi",
    #             ],  # annotationdbi was missing
    #             "imports": [],
    #             "linking_to": [],
    #             "needs_compilation": False,
    #         }
    #     ],
    #     "software": [
    #         {
    #             "name": "inSilicoMerging",
    #             "version": "1.10.1",
    #             "depends": [
    #                 "Biobase",
    #                 "inSilicoDb",
    #                 "BiocGenerics",
    #             ],  # inSilicoDb was missing
    #             "imports": [],
    #             "linking_to": [],
    #             "needs_compilation": False,
    #         }
    #     ],
    # }
}

additional_r_dependencies = {
    # for when stuff is missing...
    # we need to use this already at low level,
    # so the graph is complete,
    # not only on export
    "3.0": {
        "annotation": {"gahgu133plus2cdf": ["AnnotationDbi"]},
        "software": {"inSilicoMerging": ["inSilicoDb"]},
    }
}


native_build_inputs = {  # ie. compile time dependencies
    # pkgs. get's added automatically if there's no . in the entry.
    "3.0": {
        "abn": ["gsl"],
        "adimpro": ["imagemagick"],
        "affyio": ["zlib"],
        "ArrayExpressHTS": ["which"],
        "audio": ["portaudio"],
        "BayesSAE": ["gsl"],
        "BayesVarSel": ["gsl"],
        "BayesXsrc": ["readline", "ncurses"],
        # "bigGP": ["openmpi"],
        "BiocCheck": ["which"],
        "Biostrings": ["zlib"],
        # "BitSeq": ["zlib"],
        "bnpmr": ["gsl"],
        "BNSP": ["gsl"],
        "cairoDevice": ["gtk2"],
        "Cairo": ["libtiff", "libjpeg", "cairo"],
        # "Cardinal": ["which"],
        "CARramps": ["pkgs.linuxPackages.nvidia_x11", "liblapack"],
        "chebpol": ["fftw"],
        "ChemmineOB": ["openbabel", "pkgconfig"],
        "cit": ["gsl"],
        "Crossover": ["which"],
        # "curl": ["curl"],
        "devEMF": ["pkgs.xlibs.libXft"],
        # "DiffBind": ["zlib"],
        "DirichletMultinomial": ["gsl"],
        "diversitree": ["gsl", "fftw"],
        "eiR": ["gsl"],
        "EMCluster": ["liblapack"],
        "fftw": ["fftw"],
        "fftwtools": ["fftw"],
        "flowQ": ["imagemagick"],
        "Formula": ["gmp"],
        "geoCount": ["gsl"],
        # "git2r": ["zlib", "openssl"],
        "GLAD": ["gsl"],
        "glpkAPI": ["gmp", "glpk"],
        "gMCP": ["which"],
        "gmp": ["gmp"],
        # "graphscan": ["gsl"],
        "gsl": ["gsl"],
        "HiCseg": ["gsl"],
        # "HilbertVisGUI": ["pkgconfig", "opencl-headers"],
        "iBMQ": ["gsl"],
        "igraph": ["gmp"],
        "JavaGD": ["jdk"],
        "jpeg": ["libjpeg"],
        "KFKSDS": ["gsl"],
        "kza": ["fftw"],
        "libamtrack": ["gsl"],
        "ltsk": ["liblapack", "blas"],
        "mixcat": ["gsl"],
        "MMDiff": ["gsl"],
        "MotIV": ["openssl", "gsl"],
        "motifStack": ["gsl"],
        "MSGFplus": ["jdk"],
        "mvabund": ["gsl"],
        "mwaved": ["fftw"],
        "mzR": ["zlib", "netcdf"],
        "ncdf4": ["netcdf"],
        # "ncdfFlow": ["hdf5.dev"],
        "ncdf": ["netcdf"],
        "nloptr": ["nlopt"],
        "npRmpi": ["openmpi"],
        # "openssl": ["openssl"],
        "outbreaker": ["gsl"],
        "pander": ["pandoc", "which"],
        "pbdMPI": ["openmpi"],
        "pbdNCDF4": ["netcdf"],
        "pbdPROF": ["openmpi"],
        "pbdSLAP": ["openmpi"],
        "PBSmapping": ["which"],
        "PBSmodelling": ["which"],
        "pcaPA": ["gsl"],
        "PICS": ["gsl"],
        "PING": ["gsl"],
        "PKI": ["openssl"],
        "png": ["libpng"],
        "PopGenome": ["zlib"],
        "proj4": ["proj"],
        "qtbase": ["qt4"],
        "qtpaint": ["qt4"],
        "R2GUESS": ["gsl"],
        "R2SWF": ["zlib", "libpng", "freetype"],
        "RapidPolygonLookup": ["which"],
        "RAppArmor": ["libapparmor"],
        "rapportools": ["which"],
        "rapport": ["which"],
        "rbamtools": ["zlib"],
        "RCA": ["gmp"],
        "rcdd": ["gmp"],
        "RcppCNPy": ["zlib"],
        "RcppGSL": ["gsl"],
        "RcppOctave": ["zlib", "bzip2", "icu", "lzma", "pcre", "octave"],
        "RcppRedis": ["hiredis"],
        "RcppZiggurat": ["gsl"],
        # "ReQON": ["zlib"],
        "rgdal": ["proj", "gdal"],
        "rgeos": ["geos"],
        "rggobi": ["ggobi", "gtk2", "libxml2"],
        "rgl": ["mesa", "x11"],
        "Rglpk": ["glpk"],
        "rgpui": ["which"],
        "rgp": ["which"],
        "RGtk2": ["gtk2"],
        # "rhdf5": ["hdf5.dev"],
        "Rhpc": ["zlib", "bzip2", "icu", "lzma", "openmpi", "pcre"],
        # "Rhtslib": ["zlib"],
        "ridge": ["gsl"],
        "RJaCGH": ["zlib"],
        "rjags": ["jags"],
        "rJava": [
            "zlib",
            "bzip2",
            "icu",
            "lzma",
            "pcre",
            "jdk",
            "libzip",
        ],
        # "Rlibeemd": ["gsl"],
        "rMAT": ["gsl"],
        # "rmatio": ["zlib"],
        "Rmpfr": ["gmp", "mpfr"],
        "Rmpi": ["openmpi"],
        "RMySQL": ["zlib", "pkgs.mysql.lib"],
        "RnavGraph": ["xlibsWrapper"],
        "RNetCDF": ["netcdf", "udunits"],
        "Rniftilib": ["zlib", "openmpi"],
        "RODBCext": ["libiodbc"],
        "RODBC": ["libiodbc"],
        "rpanel": ["tk"],
        "rpg": ["postgresql"],
        "rphast": ["pcre", "zlib", "bzip2", "gzip", "readline"],
        "Rpoppler": ["poppler"],
        "RPostgreSQL": ["postgresql"],
        "RProtoBuf": ["protobuf"],
        "rpud": ["pkgs.linuxPackages.nvidia_x11"],
        "rPython": ["python"],
        "RQuantLib": ["hquantlib"],
        "Rsamtools": ["zlib"],
        "RSclient": ["openssl"],
        "Rserve": ["openssl"],
        "Rssa": ["fftw"],
        "rTANDEM": ["expat"],
        "rtfbs": ["zlib", "pcre", "bzip2", "gzip", "readline"],
        "rtiff": ["libtiff"],
        "runjags": ["jags"],
        "RVowpalWabbit": ["zlib", "boost"],
        "rzmq": ["zeromq3"],
        "SAVE": ["zlib", "bzip2", "icu", "lzma", "pcre"],
        "sdcTable": ["gmp", "glpk"],
        "seewave": ["fftw", "libsndfile"],
        "SemiCompRisks": ["gsl"],
        # "seqbias": ["zlib"],
        # "seqinr": ["zlib"],
        "seqminer": ["zlib", "bzip2"],
        "seqTools": ["zlib"],
        # "seqTools": ["zlib"],
        # "ShortRead": ["zlib"],
        "showtext": ["zlib", "libpng", "icu", "freetype"],
        "simplexreg": ["gsl"],
        "SJava": ["jdk"],
        "snpStats": ["zlib"],
        "SOD": ["cudatoolkit"],
        "spate": ["fftw"],
        "sprint": ["openmpi"],
        "ssanv": ["proj"],
        "STARSEQ": ["zlib"],
        "stsm": ["gsl"],
        "survSNP": ["gsl"],
        "sysfonts": ["zlib", "libpng", "freetype"],
        "TAQMNGR": ["zlib"],
        "tiff": ["libtiff"],
        # "TKF": ["gsl"],
        "tkrplot": ["pkgs.xlibs.libX11"],
        "topicmodels": ["gsl"],
        "udunits2": ["udunits", "expat"],
        # "V8": ["v8"],
        "VBLPCM": ["gsl"],
        "VBmix": ["gsl", "fftw", "qt4"],
        "vcf2geno": ["zlib"],
        # "WhopGenome": ["zlib"],
        "XBRL": ["zlib", "libxml2"],
        # "xml2": ["libxml2"],
        "XML": ["libtool", "libxml2", "xmlsec", "libxslt"],
    }
}

build_inputs = {  # run time dependencies
    # note that in here, it's still 'r packages names', so 'nat.blast', not 'nat_blast'
    "3.0": {
        # sort -t '=' -k 2
        "adimpro": ["which", "pkgs.xorg.xdpyinfo"],
        "cairoDevice": ["pkgconfig"],
        "Cairo": ["pkgconfig"],
        "CARramps": ["which", "cudatoolkit"],
        "chebpol": ["pkgconfig"],
        "dti": ["which", "pkgs.xorg.xdpyinfo", "imagemagick"],
        "ecoretriever": ["which"],
        "flowQ": [
            "imagemagick"
        ],  # pretty sure it's going to need this during runtime as well
        "fftw": ["pkgconfig"],
        "geoCount": ["pkgconfig"],
        "gmatrix": ["cudatoolkit"],
        "gputools": ["which", "cudatoolkit"],
        # "gridGraphics": ["which"],
        "kza": ["pkgconfig"],
        "MSGFgui": ["jdk"],
        "mwaved": ["pkgconfig"],
        "nat.nblast": ["which"],
        "nat": ["which"],
        "nat.templatebrains": ["which"],
        "PET": ["which", "pkgs.xorg.xdpyinfo", "imagemagick"],
        "qtbase": ["cmake", "perl"],
        "qtpaint": ["cmake"],
        "qtutils": ["qt4"],
        "R2SWF": ["pkgconfig"],
        "RCurl": ["curl"],
        "rggobi": ["pkgconfig"],
        "RGtk2": ["pkgconfig"],
        "RMark": ["which"],
        "Rpoppler": ["pkgconfig"],
        "RProtoBuf": ["pkgconfig"],
        "rpud": ["which", "cudatoolkit"],
        "RPushbullet": ["which"],
        "rPython": ["which"],
        "Rsymphony": ["pkgconfig", "doxygen", "graphviz", "subversion"],
        "showtext": ["pkgconfig"],
        "spate": ["pkgconfig"],
        "stringi": ["pkgconfig"],
        "svKomodo": ["which"],
        "sysfonts": ["pkgconfig"],
        "tcltk2": ["tcl", "tk"],
        "tikzDevice": ["which", "texLive"],
        "VBmix": ["pkgconfig"],
        "WideLM": ["cudatoolkit"],
        "XML": ["pkgconfig"],
    }
}

skip_check = {
    "3.0": [
        "Rmpi",  # tries to run MPI processes
        "gmatrix",  # requires CUDA runtime
        "sprint",
        "pbdMPI",  # tries to run MPI processes  # tries to run MPI processes
    ]
}


needs_x = set(  # let's presume they never go from 'need X' no 'not need X'
    # so no per version
    # having one of these in your 'suggests'
    # will make you requireX on installation
    # (we don't go for full transitivity here
    # because building anything with X is *slow*)
    [
        "tcltk",
        "tcltk2",
        "gWidgets2RGtk2",
        "gWidgets2tcltk",
        "gWidgetsRGtk2",
        "gWidgetstcltk",
        "tkrplot",
        "cairoDevice",
        "RGtk2",
        "geoR",
        "qtbase",
        # "vegan",  # which 'suggests' tcltk
        "iplots",
        "rgeos",
        "Deducer",
        "mutossGUI",
        # endless tcl loops otherwise
        "Geneland",
        "RcmdrPlugin.ROC",
        "spatsurv",
        "ProbForecastGOP",
        "GeoGenetix",
    ]
)

set(
    [
        "accrual",
        "Actigraphy",
        "ade4TkGUI",
        "adehabitat",
        "analogue",
        "analogueExtra",
        "AnalyzeFMRI",
        "AnnotLists",
        "AnthropMMD",
        "aplpack",
        "aqfig",
        "arf3DS4",
        "asbio",
        "AtelieR",
        "BAT",
        "bayesDem",
        "BCA",
        "BEQI2",
        "betapart",
        "betaper",
        "BHMSMAfMRI",
        "BiodiversityR",
        "BioGeoBEARS",
        "bio_infer",
        "bipartite",
        "biplotbootGUI",
        "blender",
        "cairoDevice",
        "CCTpack",
        "cncaGUI",
        "cocorresp",
        "CommunityCorrelogram",
        "confidence",
        "constrainedKriging",
        "ConvergenceConcepts",
        "cpa",
        "DALY",
        "dave",
        "debug",
        "Deducer",
        "DeducerExtras",
        "DeducerPlugInExample",
        "DeducerPlugInScaling",
        "DeducerSpatial",
        "DeducerSurvival",
        "DeducerText",
        "Demerelate",
        "DescTools",
        "detrendeR",
        "dgmb",
        "DivMelt",
        "dpa",
        "DSpat",
        "dynamicGraph",
        "dynBiplotGUI",
        "EasyqpcR",
        "EcoVirtual",
        "ENiRG",
        "EnQuireR",
        "eVenn",
        "exactLoglinTest",
        "FAiR",
        "fat2Lpoly",
        "fbati",
        "FD",
        "feature",
        "FeedbackTS",
        "FFD",
        "fgui",
        "fisheyeR",
        "fit4NM",
        "forams",
        "forensim",
        "FreeSortR",
        "fscaret",
        "fSRM",
        "gcmr",
        "Geneland",
        "GeoGenetix",
        "geomorph",
        "geoR",
        "geoRglm",
        "georob",
        "GeoXp",
        "GGEBiplotGUI",
        "gnm",
        "GPCSIV",
        "GrammR",
        "GrapheR",
        "GroupSeq",
        "gsubfn",
        "GUniFrac",
        "gWidgets2RGtk2",
        "gWidgets2tcltk",
        "gWidgetsRGtk2",
        "gWidgetstcltk",
        "HH",
        "HiveR",
        "HomoPolymer",
        "iBUGS",
        "ic50",
        "iDynoR",
        "in2extRemes",
        "iplots",
        "isopam",
        "IsotopeR",
        "JGR",
        "KappaGUI",
        "lefse",
        "likeLTD",
        "loe",
        "logmult",
        "LS2Wstat",
        "MAR1",
        "MareyMap",
        "memgene",
        "MergeGUI",
        "metacom",
        "Meth27QC",
        "MetSizeR",
        "MicroStrategyR",
        "MigClim",
        "migui",
        "miniGUI",
        "MissingDataGUI",
        "mixsep",
        "mlDNA",
        "MplusAutomation",
        "mpmcorrelogram",
        "mritc",
        "MTurkR",
        "multgee",
        "multibiplotGUI",
        "mutossGUI",
        "nodiv",
        "OligoSpecificitySystem",
        "onemap",
        "OpenRepGrid",
        "palaeoSig",
        "paleoMAS",
        "pbatR",
        "PBSadmb",
        "PBSmodelling",
        "PCPS",
        "pez",
        "phylotools",
        "picante",
        "PKgraph",
        "PKmodelFinder",
        "playwith",
        "plotSEMM",
        "plsRbeta",
        "plsRglm",
        "pmg",
        "PoMoS",
        "PopGenReport",
        "poppr",
        "powerpkg",
        "PredictABEL",
        "prefmod",
        "PrevMap",
        "ProbForecastGOP",
        "QCAGUI",
        "qtbase",
        "qtpaint",
        "qtutils",
        "R2STATS",
        "r4ss",
        "RandomFields",
        "rareNMtests",
        "rAverage",
        "Rcmdr",
        "RcmdrPlugin_BCA",
        "RcmdrPlugin_coin",
        "RcmdrPlugin_depthTools",
        "RcmdrPlugin_DoE",
        "RcmdrPlugin_doex",
        "RcmdrPlugin_EACSPIR",
        "RcmdrPlugin_EBM",
        "RcmdrPlugin_EcoVirtual",
        "RcmdrPlugin_epack",
        "RcmdrPlugin_EZR",
        "RcmdrPlugin_FactoMineR",
        "RcmdrPlugin_HH",
        "RcmdrPlugin_IPSUR",
        "RcmdrPlugin_KMggplot2",
        "RcmdrPlugin_lfstat",
        "RcmdrPlugin_MA",
        "RcmdrPlugin_mosaic",
        "RcmdrPlugin_MPAStats",
        "RcmdrPlugin_orloca",
        "RcmdrPlugin_plotByGroup",
        "RcmdrPlugin_pointG",
        "RcmdrPlugin_qual",
        "RcmdrPlugin_ROC",
        "RcmdrPlugin_sampling",
        "RcmdrPlugin_SCDA",
        "RcmdrPlugin_SLC",
        "RcmdrPlugin_SM",
        "RcmdrPlugin_sos",
        "RcmdrPlugin_StatisticalURV",
        "RcmdrPlugin_steepness",
        "RcmdrPlugin_survival",
        "RcmdrPlugin_TeachingDemos",
        "RcmdrPlugin_temis",
        "RcmdrPlugin_UCA",
        "recluster",
        "relax",
        "relimp",
        "RenextGUI",
        "reportRx",
        "reshapeGUI",
        "rgl",
        "RHRV",
        "rich",
        "ringscale",
        "rioja",
        "ripa",
        "rite",
        "rnbn",
        "RnavGraph",
        "RNCEP",
        "RQDA",
        "RSDA",
        "rsgcc",
        "RSurvey",
        "RunuranGUI",
        "sdcMicroGUI",
        "SeqGrapheR",
        "sharpshootR",
        "simba",
        "Simile",
        "SimpleTable",
        "SOLOMON",
        "soundecology",
        "SPACECAP",
        "spacodiR",
        "spatsurv",
        "sqldf",
        "SRRS",
        "SSDforR",
        "statcheck",
        "StatDA",
        "STEPCAM",
        "stosim",
        "strvalidator",
        "stylo",
        "svDialogstcltk",
        "svIDE",
        "svSocket",
        "svWidgets",
        "SYNCSA",
        "SyNet",
        "tcltk2",
        "TDMR",
        "TED",
        "TestScorer",
        "TIMP",
        "titan",
        "tkrgl",
        "tkrplot",
        "tmap",
        "tspmeta",
        "TTAinterfaceTrendAnalysis",
        "twiddler",
        "vcdExtra",
        "VecStatGraphs3D",
        "vegan",
        "vegan3d",
        "vegclust",
        "VIMGUI",
        "WMCapacity",
        "x12GUI",
        "xergm",
    ]
)
